version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: jicv32sd
  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - 5050:5050
  web:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db