# Generated by Django 2.2.2 on 2019-06-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0002_auto_20190628_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prodBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brandname', to='brands.Brands'),
        ),
        migrations.AddField(
            model_name='products',
            name='prodCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryname', to='categories.Categories'),
        ),
    ]
