# Generated by Django 2.2.2 on 2019-06-28 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190628_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brandname', to='brands.Brands', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryname', to='categories.Categories', verbose_name='Categoria'),
        ),
    ]
