# Generated by Django 2.2.2 on 2019-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0006_productstypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prodCat',
        ),
        migrations.AddField(
            model_name='products',
            name='prodCat',
            field=models.ManyToManyField(blank=True, null=True, related_name='categoryname', to='categories.Categories', verbose_name='Categoria'),
        ),
    ]
