# Generated by Django 2.2.2 on 2019-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190629_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodCat',
            field=models.ManyToManyField(related_name='categoryname', to='categories.Categories', verbose_name='Categoria'),
        ),
    ]
